export const currencies = [
  {
    countryFlag: '🇦🇺',
    Id: 'con-1',
    countryName: 'Australia',
    countryCurrency: 'AUD',
    exchangeRate: 53.27,
  },
  {
    countryFlag: '🇨🇦',
    Id: 'con-2',
    countryName: 'Canada',
    countryCurrency: 'CAD',
    exchangeRate: 55.68,
  },
  {
    countryFlag: '🇨🇳',
    Id: 'con-3',
    countryName: 'China',
    countryCurrency: 'CNY',
    exchangeRate: 11.61,
  },
  {
    countryFlag: '🇪🇺',
    Id: 'con-4',
    countryName: 'European Union',
    countryCurrency: 'EUR',
    exchangeRate: 90.19,
  },
  {
    countryFlag: '🇭🇰',
    Id: 'con-5',
    countryName: 'Hong Kong',
    countryCurrency: 'HKD',
    exchangeRate: 9.59,
  },
  {
    countryFlag: '🇮🇩',
    Id: 'con-6',
    countryName: 'Indonesia',
    countryCurrency: 'IDR',
    exchangeRate: 0.0052,
  },
  {
    countryFlag: '🇮🇳',
    Id: 'con-7',
    countryName: 'India',
    countryCurrency: 'INR',
    exchangeRate: 1,
  },
  {
    countryFlag: '🇯🇵',
    Id: 'con-8',
    countryName: 'Japan',
    countryCurrency: 'JPY',
    exchangeRate: 0.67,
  },
  {
    countryFlag: '🇰🇷',
    Id: 'con-9',
    countryName: 'South Korea',
    countryCurrency: 'KRW',
    exchangeRate: 0.062,
  },
  {
    countryFlag: '🇲🇾',
    Id: 'con-10',
    countryName: 'Malaysia',
    countryCurrency: 'MYR',
    exchangeRate: 17.98,
  },
  {
    countryFlag: '🇵🇭',
    Id: 'con-11',
    countryName: 'Philippines',
    countryCurrency: 'PHP',
    exchangeRate: 1.53,
  },
  {
    countryFlag: '🇸🇬',
    Id: 'con-12',
    countryName: 'Singapore',
    countryCurrency: 'SGD',
    exchangeRate: 54.92,
  },
  {
    countryFlag: '🇿🇦',
    Id: 'con-13',
    countryName: 'South Africa',
    countryCurrency: 'ZAR',
    exchangeRate: 4.92,
  },
  {
    countryFlag: '🇪🇸',
    Id: 'con-14',
    countryName: 'Spain',
    countryCurrency: 'EUR',
    exchangeRate: 90.19,
  },
  {
    countryFlag: '🇹🇼',
    Id: 'con-15',
    countryName: 'Taiwan',
    countryCurrency: 'TWD',
    exchangeRate: 2.64,
  },
  {
    countryFlag: '🇹🇭',
    Id: 'con-16',
    countryName: 'Thailand',
    countryCurrency: 'THB',
    exchangeRate: 2.35,
  },
  {
    countryFlag: '🇬🇧',
    Id: 'con-17',
    countryName: 'United Kingdom',
    countryCurrency: 'GBP',
    exchangeRate: 98.38,
  },
  {
    countryFlag: '🇺🇸',
    Id: 'con-18',
    countryName: 'United States',
    countryCurrency: 'USD',
    exchangeRate: 74.71,
  },
  {
    countryFlag: '🇻🇳',
    Id: 'con-19',
    countryName: 'Vietnam',
    countryCurrency: 'VND',
    exchangeRate: 0.0032,
  },
  {
    countryFlag: '🇧🇷',
    Id: 'con-20',
    countryName: 'Brazil',
    countryCurrency: 'BRL',
    exchangeRate: 14.29,
  },
];
